### ISSUE TITLE
Please add Astroseries to the list of Stratagus-based games

### ISSUE THREAD

**Issue by SenhorFlibble** [Wargus/Wargus.github.io#10]
Not sure if this is the right place to post, but could you please add Alvaro F. Perez' Astroseries to the list of games that run on the Stratagus engine on [this page](https://stratagus.com/stratagus.html)? It uses an old engine version (2.1), but is feature-complete with two full singleplayer campaigns and some skirmish maps as well.

Recently I picked the latest available version of Astroseries, v1.31, from SourceForge, and cleaned it up from leftover proprietary data, as well as fixed a couple of bugs, including one that caused sound playback to disappear if a campaign scenario was restarted.

The cleaned up and bugfixed version is available here:
https://github.com/SenhorFlibble/Astroseries/releases/tag/v1.31b

**Comment by timfel** [comment]
Will do. Should I just link to your github?

**Comment by SenhorFlibble** [comment]
Yes please -- the older SF version contains leftover proprietary data as I mentioned above.

Thanks!

**Comment by timfel** [comment]
Done 🙂
