### ISSUE TITLE
Add War1gus page

### ISSUE THREAD

**Issue by timfel** [Wargus/Wargus.github.io#2]
War1gus is working (in the sense that you can play through the campaigns, the editor, and skirmish battles against AI and human players work). So it'd be cool to have that on the Website, too :)

**Comment by mimooh** [comment]
If you don't add this info, then I'll add it later. Perhaps you could
make a screenshot of war1gus? I think screenshot are a good thing.

## 

Karol Kreński

**Comment by timfel** [comment]
Thanks :)

You mean like the pictures on the https://github.com/Wargus/war1gus readme?

**Comment by mimooh** [comment]
> You mean like the pictures on the https://github.com/Wargus/war1gus readme?
> War1gus doesn't look pretty :) If it is to be attractive perhaps a
> screenshot of a high resolution game like I made for Wargus would be
> better? http://wargus.github.io/img/screenshot.png

If you think people are interested in War1gus I can make a separate page
for it, similar to the site about Wargus. I will make one for Aleona
too, but Wyrmsun will be just redirected, unless Andrettin would like
otherwise. Andrettin, are you reading this?

## 

Karol Kreński

**Comment by timfel** [comment]
How about these screenshots?

<img width="841" alt="capture" src="https://cloud.githubusercontent.com/assets/46235/13456021/34948bbe-e061-11e5-926e-8ac70b695d68.PNG">
<img width="841" alt="capture2" src="https://cloud.githubusercontent.com/assets/46235/13456023/349a6f0c-e061-11e5-8490-7af21f676841.PNG">
<img width="841" alt="capture3" src="https://cloud.githubusercontent.com/assets/46235/13456022/349638c4-e061-11e5-82eb-b683b2d115f6.PNG">

**Comment by mimooh** [comment]
These are fine :) I think just one is fine. OK, we will have a site for
war1gus too. I will make it based on wargus informations, except I won't
comment on things I am not sure (gameplay, benefits over original).

## 

Karol Kreński

**Comment by mimooh** [comment]
war1gus and aleona sites are in github. After we decide where aleona
belongs in the wargus project I will update the site.

## 

Karol Kreński
